# Generated by Django 4.2.6 on 2023-10-08 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    default='db6e7efaaaee47f1a72c3143a563d28d', max_length=16)),
                ('website_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('landline_number', models.CharField(max_length=8, null=True)),
                ('address_one', models.CharField(max_length=20, null=True)),
                ('address_two', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.ForeignKey(db_column='updated_by',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metadata',
            },
        ),
    ]
