# Generated by Django 4.2.6 on 2023-10-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='reference_id',
            field=models.CharField(default='7b6622ad96ac43c088ed8be8e57348f9', max_length=16),
        ),
    ]
