# Generated by Django 4.2.6 on 2023-10-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_metadata_is_delete_alter_metadata_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='reference_id',
            field=models.CharField(default='6e1408ff293943dc8de3bc613e11637e', max_length=20),
        ),
    ]
