# Generated by Django 4.2.6 on 2023-10-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_alter_metadata_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='reference_id',
            field=models.CharField(default='785f2b6f7f9844f5ad407ee57b61c5b9', max_length=32),
        ),
    ]
