# Generated by Django 4.2.6 on 2023-10-09 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0004_alter_metadata_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='reference_id',
            field=models.CharField(default='79fe675572e247a9a1ab0a7006ec161a', max_length=32),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
