# Generated by Django 4.2.6 on 2023-10-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_alter_metadata_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='reference_id',
            field=models.CharField(default='9b121a38814546879a10588e2dad3ef1', max_length=32),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
