# Generated by Django 4.2.6 on 2023-11-05 21:16
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    default=uuid.uuid4().hex, max_length=32)),
                ('client_name', models.CharField(max_length=45)),
                ('logo_url', models.ImageField(upload_to='uploads/clients/')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
